# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 放置演算子
email: fujii@xaxxi.net
description: > # this means to ignore newlines until "baseurl:"
  kikei.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kikei.github.io" # the base hostname & protocol for your site
github_username:  kikei

# Build settings
timezone: Asia/Tokyo
markdown: kramdown

gems:
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed

